spring:
  application:
    name: Work_with_properties_Spring_Boot
  profiles:
    active: dev

app:
  name: "My Application"
  version: "1.0.0"
  features:
    enabled: true
    max-items: 100
  security:
    api-key: "secret-key-12345"
    allowed-origins:
      - "http://localhost:8080"
      - "https://myapp.com"
  database:
    url: "jdbc:postgresql://localhost:5432/mydb"
    username: "admin"
    timeout: 5000
  notification:
    email:
      host: "smtp.gmail.com"
      port: 587
      from: "noreply@myapp.com"
  # Новые примеры
  endpoints:
    endpoints:
      users: "/api/users"
      orders: "/api/orders"
      products: "/api/products"
  feature-flags:
    featureFlags:
      dark-mode: true
      beta-features: false
      new-ui: true
  retry-config:
    max-attempts: 3
    delays:
      - 1000
      - 2000
      - 5000
  cache:
    ttl-settings:
      users: 3600
      products: 7200
      orders: 1800
  cors:
    settings:
      "http://localhost:3000":
        allowed-methods: ["GET", "POST"]
        max-age: 3600
      "https://admin.myapp.com":
        allowed-methods: ["GET", "POST", "PUT", "DELETE"]
        max-age: 7200
  environment-specific:
    environmentSpecific:
      dev:
        logging-level: "DEBUG"
        mock-services: true
      prod:
        logging-level: "INFO"
        mock-services: false